# Generated by Django 3.1.2 on 2023-01-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                (
                'message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_number', models.IntegerField()),
                ('sender_display_name', models.CharField(default=None, max_length=50, null=True)),
                ('sender_number', models.IntegerField()),
                ('message_type', models.CharField(default=None, max_length=50)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('media_id', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=None, null=True)),
                ('related_message_id', models.ForeignKey(blank=True, null=True,
                                                         on_delete=django.db.models.deletion.CASCADE,
                                                         to='customer.whatsappmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['received_at'], name='customer_wh_receive_8fb812_idx'),
        ),
    ]
