# Generated by Django 3.1.2 on 2023-01-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0002_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_payload',
            field=models.JSONField(default=None, null=True),
        ),
    ]
