# Generated by Django 3.1.2 on 2023-01-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0003_whatsappmessage_sent_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='payload',
            field=models.JSONField(default=None, null=True, verbose_name='Received Payload'),
        ),
    ]
