# Generated by Django 3.1.2 on 2023-03-13 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0009_bill_mongo_id'),
        ('customer', '0004_rename_payload_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='seller',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='register.tenant'),
        ),
        migrations.AlterField(
            model_name='loginotp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='register.customer'),
        ),
    ]
