# Generated by Django 4.2.1 on 2023-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_add_seller_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginotp",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
