# Generated by Django 4.2 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_add_id_field_to_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='oci_object_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
