# Generated by Django 3.1.2 on 2022-08-18 12:11

import uuid

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('register', '0004_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('bill_number', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=25)),
                ('status_msg', models.CharField(default='', max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('online_transaction_id', models.CharField(max_length=255)),
                ('raw_resp', jsonfield.fields.JSONField(default=None)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               to='register.customer')),
            ],
        ),
    ]
