# Generated by Django 4.2.1 on 2023-07-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("register", "0010_alter_add_id_field_to_all_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("lending_date", models.DateTimeField()),
                ("status", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="register.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PRINCIPAL", "Principal"), ("INTEREST", "Interest")],
                        default="INTEREST",
                        max_length=10,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "loan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="loan.loan"
                    ),
                ),
            ],
        ),
    ]
