# Generated by Django 3.1.2 on 2020-10-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('morning', models.BooleanField(default=True)),
                ('evening', models.BooleanField(default=True)),
                ('quantity', models.FloatField(default=None)),
                ('status', models.BooleanField(default=True)),
                ('member_since', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_effective', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('morning', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('quantity', models.FloatField(default=None)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.customer')),
            ],
        ),
    ]
