# Generated by Django 3.1.2 on 2021-08-29 16:14

import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('morning', models.BooleanField(default=True)),
                ('evening', models.BooleanField(default=True)),
                ('m_quantity', models.IntegerField(default=None, null=True)),
                ('e_quantity', models.IntegerField(default=None, null=True)),
                ('status', models.BooleanField(default=True)),
                ('member_since', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant',
                 models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                      primary_key=True, serialize=False, to='auth.user')),
                ('download_pdf_pref', models.BooleanField(default=True)),
                ('sms_pref', models.BooleanField(default=True)),
                ('whatsapp_pref', models.BooleanField(default=True)),
                ('whatsapp_direct_pref', models.BooleanField(default=True)),
                ('email_pref', models.BooleanField(default=False)),
                ('customers_bill_access', models.BooleanField(default=True)),
                ('bill_till_date', models.BooleanField(default=True)),
                ('milk_price',
                 models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('date_effective', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('schedule', models.CharField(default=None, max_length=15, null=True)),
                ('quantity', models.FloatField(default=None)),
                ('current_price',
                 models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                               to='register.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='register.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('log_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                               to='register.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='register.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('log_date', models.DateTimeField(default=datetime.datetime.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='register.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('log_date', models.DateTimeField(default=datetime.datetime.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='register.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('bill_number', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_last_data_date', models.DateTimeField()),
                ('bill_generated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='register.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                  primary_key=True, serialize=False,
                                                  to='register.customer')),
                (
                    'balance_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='register.tenant')),
            ],
        ),
    ]
