# Generated by Django 3.1.2 on 2022-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='e_quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='m_quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='schedule',
            field=models.CharField(choices=[('morning-yes', 'Morning Present'), ('morning-no', 'Morning Absent'), ('evening-yes', 'Evening Present'), ('evening-yes', 'Evening Absent')], default=None, max_length=15, null=True),
        ),
    ]
