# Generated by Django 3.1.2 on 2021-02-07 12:22

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0002_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
        migrations.AddField(
            model_name='income',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
        migrations.AddField(
            model_name='milk',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
        migrations.AddField(
            model_name='register',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='register.tenant'),
        ),
    ]
