# Generated by Django 3.1.2 on 2022-03-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_admin_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='last_balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10,
                                      null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='transaction_number',
            field=models.ForeignKey(blank=True, default=None, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='register.payment'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       primary_key=True, serialize=False, to='register.customer'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.tenant'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.tenant'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.tenant'),
        ),
        migrations.AlterField(
            model_name='income',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.tenant'),
        ),
        migrations.AlterField(
            model_name='register',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.customer'),
        ),
        migrations.AlterField(
            model_name='register',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='register',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='register.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT,
                                       primary_key=True, serialize=False,
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
