# Generated by Django 3.1.2 on 2021-02-07 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0003_auto_20210207_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milk',
        ),
    ]
