# Generated by Django 3.1.2 on 2022-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0003_transaction_revert'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, default='CASH', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
