# Generated by Django 3.1.2 on 2022-08-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0004_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accept_online_payment',
            field=models.BooleanField(default=False),
        ),
    ]
