# Generated by Django 3.1.2 on 2021-02-09 10:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0005_auto_20210207_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_direct_pref',
            field=models.BooleanField(default=True),
        ),
    ]
