# Generated by Django 3.1.2 on 2022-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0005_tenant_accept_online_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='schedule',
            field=models.CharField(
                choices=[('morning-yes', 'Morning Present'), ('morning-no', 'Morning Absent'),
                         ('evening-yes', 'Evening Present'), ('evening-no', 'Evening Absent')],
                default=None, max_length=15, null=True),
        ),
    ]
