# Generated by Django 3.1.2 on 2022-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0006_update_schedule_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
