# Generated by Django 3.1.2 on 2023-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0007_add_seller_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_notes',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
