# Generated by Django 3.1.2 on 2021-03-14 14:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0007_tenant_bill_till_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='customers_bill_access',
            field=models.BooleanField(default=True),
        ),
    ]
