# Generated by Django 4.2.30 on 2026-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_add_id_field_to_all_models'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(models.F('tenant'), models.F('customer'), models.F('log_date'), models.Case(models.When(schedule__startswith='morning', then=models.Value('morning')), models.When(schedule__startswith='evening', then=models.Value('evening')), default=models.F('schedule')), name='unique_customer_delivery_period'),
        ),
    ]
