name: MilkBasket Deploy

env:
  project: MilkBasket
  server: https://cyberboy.octopus.app/

on:
  push:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Octopus Command-Line Interface
        run: sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https &&
             curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - &&
             sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" &&
             sudo apt update && sudo apt install octopuscli
             
      - name: Create Octopus release
        run: |
          octo create-release --server ${{ env.server }} --apiKey ${{ secrets.OCTOPUS_API_KEY }} --project ${{ env.project }} --version $(date +%Y.%m.%d)

      - name: Deploy to environment
        run: |
          octo deploy-release --server ${{ env.server }} --apiKey ${{ secrets.OCTOPUS_API_KEY }} --project ${{ env.project }} --releaseNumber $(date +%Y.%m.%d) --deployTo Production
