name: MilkBasket Deploy

env:
  project: MilkBasket
  server: https://cyberboy.octopus.app/

on:
  push:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Octopus Command-Line Interface
        run: sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https &&
             curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - &&
             sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" &&
             sudo apt update && sudo apt install octopuscli
             
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      - name: Create Octopus release
        run: |
          octo create-release `
          --server ${{ env.server }} `
          --apiKey ${{ secrets.OCTOPUS_API_KEY }} `
          --project ${{ env.project }} `
          --version ${{ steps.commit_hash.outputs.hash }}

      - name: Deploy to environment
        run: |
          octo deploy-release `
          --server ${{ env.server }} `
          --apiKey ${{ secrets.OCTOPUS_API_KEY }} `
          --project ${{ env.project }} `
          --releaseNumber ${{ steps.commit_hash.outputs.hash }} `
          --deployTo Production
